services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pixli
      MONGO_INITDB_ROOT_PASSWORD: pixli
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
